data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'plomber'
    dataset: retail
soda_cloud:
  host: cloud.soda.io
  api_key_id: 3dbe477e-038d-4ad3-86cc-931628bff1c4
  api_key_secret: 2iv5a-mgkQEM78VtHae01WQDBG0-y2xGwOkvl1DzwR3nDPXTVQZ1ig